name: Auto Merge to Development

on:
  push:
    branches:
      - dev-sakshi1
      - dev-sakshi2
jobs:
  merge-to-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge branch into development
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin development
          git checkout development
          git merge ${{ github.ref_name }} --no-edit
          git push origin development